export const USER_GET_FROM_STORAGE = 'USER_GET_FROM_STORAGE';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const USER_LOGOUT = 'USER_LOGOUT';

export const VIDEOS_REQUEST = 'VIDEOS_REQUEST';
export const VIDEOS_GET_SUCCESS = 'VIDEOS_GET_SUCCESS';
export const VIDEOS_GET_FAILED = 'VIDEOS_GET_FAILED';

export const VIDEO_DETAIL_REQUEST = 'VIDEO_DETAIL_REQUEST';
export const VIDEO_DETAIL_SUCCESS = 'VIDEO_DETAIL_SUCCESS';
export const VIDEO_DETAIL_FAILED = 'VIDEO_DETAIL_FAILED';
